### PR TITLE
Varimax

### PR DESCRIPTION
**Pull request by ericpre**
To help to finish https://github.com/scikit-learn/scikit-learn/pull/11064.

- [x] Merge with upstream,
- [x] fix linting and deprecation warning.

CI pass: https://dev.azure.com/ericpre/scikit-learn/_build/results?buildId=241&view=results

### CODE REVIEW

**Comment by ericpre** [comment]
@jona-sassenhagen just to know if you would have time to check the merge conflict?
It not, I can open a new PR in the upstream repository, but I would prefer to have this merge, so everything in the same PR (https://github.com/scikit-learn/scikit-learn/pull/11064). Thanks!

**Comment by jona-sassenhagen** [comment]
@ericpre , sorry for being so late with this. I will try to do it on the weekend, if that's ok.

**Comment by ericpre** [comment]
@jona-sassenhagen, thanks for your reply and no worries!

**Comment by jona-sassenhagen** [comment]
Hey Eric, sorry, I didn’t manage to finish this over the weekend. I worked on it a bit and removed the merge conflicts, bit I didn’t get a testing config up locally and couldn’t get it green.

**Comment by ericpre** [comment]
Thanks @jona-sassenhagen for the update, but the merge conflicts were already solved in this PR? And the tests are passing on azure, as mentioned above (https://github.com/jona-sassenhagen/scikit-learn/pull/1#issue-364578740):
https://dev.azure.com/ericpre/scikit-learn/_build/results?buildId=241&view=results

So you just have to review it that it is fine!

**Comment by jona-sassenhagen** [comment]
I'm an idiot ...

**Comment by ericpre** [comment]
No problem, the long list of commits from upstream may have been a bit confusing/distractive! Anyway, I could have been more clear too.

**Pull request merged**
